development:
  adapter: postgresql
  encoding: unicode
  database: roodle_lms_development
  host: localhost
  pool: 5
  username: postgres
  password: postgres
  port: 5432


test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: roodle_lms_test
  pool: 5
  username: postgres
  password: postgres













